GOEMOTIONS_LABELS = [
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise",
    "neutral",
]

GOEMOTION_TO_MOOD = {
    "joy": "happy",
    "amusement": "happy",
    "gratitude": "happy",
    "love": "happy",
    "optimism": "happy",
    "pride": "happy",
    "excitement": "excited",
    "surprise": "excited",
    "sadness": "sad",
    "grief": "sad",
    "remorse": "sad",
    "disappointment": "disappointed",
    "embarrassment": "disappointed",
    "anger": "angry",
    "annoyance": "angry",
    "disapproval": "angry",
    "disgust": "angry",
    "fear": "anxious",
    "nervousness": "anxious",
    "confusion": "anxious",
    "caring": "calm",
    "relief": "calm",
    "admiration": "calm",
    "approval": "calm",
    "curiosity": "neutral",
    "desire": "neutral",
    "realization": "neutral",
    "neutral": "neutral",
}

MOOD_LABELS = ["happy", "sad", "angry", "anxious", "disappointed", "lonely", "excited", "calm", "neutral"]


def map_goemotion_to_mood(label: str) -> str:
    return GOEMOTION_TO_MOOD.get(label, "neutral")
