LANGUAGES = ["English", "Hindi", "Tamil", "Telugu", "Malayalam", "Kannada", "Bengali", "Marathi", "Punjabi", "Gujarati"]

SEED_ITEMS = [
    ("Happy", "song", "English", "happy,upbeat,feel-good", "Pop", "Pharrell Williams", 2013),
    ("Good Life", "song", "English", "happy,upbeat,hopeful", "Pop", "OneRepublic", 2010),
    ("Weightless", "song", "English", "calm,comforting", "Ambient", "Marconi Union", 2011),
    ("Paddington 2", "movie", "English", "comforting,comedy,feel-good", "Comedy", "Paul King", 2017),
    ("The Secret Life of Walter Mitty", "movie", "English", "hopeful,adventure,feel-good", "Adventure", "Ben Stiller", 2013),
    ("Sing Street", "movie", "English", "uplifting,feel-good,hopeful", "Musical", "John Carney", 2016),
    ("Ilahi", "song", "Hindi", "excited,upbeat,hopeful", "Bollywood", "Arijit Singh", 2013),
    ("Kar Har Maidaan Fateh", "song", "Hindi", "uplifting,hopeful", "Bollywood", "Sukhwinder Singh", 2018),
    ("Kun Faya Kun", "song", "Hindi", "calm,comforting", "Bollywood", "A. R. Rahman", 2011),
    ("Zindagi Na Milegi Dobara", "movie", "Hindi", "feel-good,friendship,comedy", "Drama", "Zoya Akhtar", 2011),
    ("Queen", "movie", "Hindi", "uplifting,hopeful,comedy", "Drama", "Vikas Bahl", 2013),
    ("Chhichhore", "movie", "Hindi", "uplifting,comedy,hopeful", "Comedy", "Nitesh Tiwari", 2019),
    ("Aalaporan Thamizhan", "song", "Tamil", "excited,upbeat,hopeful", "Soundtrack", "A. R. Rahman", 2017),
    ("Mental Manadhil", "song", "Tamil", "happy,upbeat", "Soundtrack", "A. R. Rahman", 2015),
    ("New York Nagaram", "song", "Tamil", "calm,comforting", "Soundtrack", "A. R. Rahman", 2006),
    ("Oh My Kadavule", "movie", "Tamil", "feel-good,comedy,hopeful", "Romcom", "Ashwath Marimuthu", 2020),
    ("Nanban", "movie", "Tamil", "friendship,comedy,uplifting", "Comedy", "Shankar", 2012),
    ("Soodhu Kavvum", "movie", "Tamil", "comedy,feel-good", "Comedy", "Nalan Kumarasamy", 2013),
    ("Butta Bomma", "song", "Telugu", "happy,upbeat", "Soundtrack", "Armaan Malik", 2020),
    ("Naatu Naatu", "song", "Telugu", "excited,upbeat", "Soundtrack", "M. M. Keeravani", 2022),
    ("Samajavaragamana", "song", "Telugu", "calm,comforting,feel-good", "Soundtrack", "Sid Sriram", 2020),
    ("Jathi Ratnalu", "movie", "Telugu", "comedy,feel-good", "Comedy", "Anudeep KV", 2021),
    ("Bommarillu", "movie", "Telugu", "comforting,feel-good,hopeful", "Drama", "Bhaskar", 2006),
    ("Pelli Choopulu", "movie", "Telugu", "feel-good,comedy,hopeful", "Romcom", "Tharun Bhascker", 2016),
    ("Malare", "song", "Malayalam", "calm,comforting", "Soundtrack", "Vijay Yesudas", 2015),
    ("Jimikki Kammal", "song", "Malayalam", "happy,upbeat", "Soundtrack", "Vineeth Sreenivasan", 2017),
    ("Pavizha Mazha", "song", "Malayalam", "calm,comforting", "Soundtrack", "K. S. Harisankar", 2019),
    ("Bangalore Days", "movie", "Malayalam", "friendship,feel-good,comforting", "Drama", "Anjali Menon", 2014),
    ("Ustad Hotel", "movie", "Malayalam", "comforting,hopeful,feel-good", "Drama", "Anwar Rasheed", 2012),
    ("Maheshinte Prathikaaram", "movie", "Malayalam", "comedy,feel-good,uplifting", "Comedy", "Dileesh Pothan", 2016),
    ("Belageddu", "song", "Kannada", "happy,upbeat", "Soundtrack", "Vijay Prakash", 2016),
    ("Karabuu", "song", "Kannada", "excited,upbeat", "Soundtrack", "Chandan Shetty", 2017),
    ("Anisuthide", "song", "Kannada", "calm,comforting", "Soundtrack", "Sonu Nigam", 2006),
    ("Kirik Party", "movie", "Kannada", "friendship,comedy,feel-good", "Comedy", "Rishab Shetty", 2016),
    ("Sarkari Hi. Pra. Shaale", "movie", "Kannada", "comforting,comedy,hopeful", "Drama", "Rishab Shetty", 2018),
    ("Dia", "movie", "Kannada", "hopeful,comforting,feel-good", "Drama", "K. S. Ashoka", 2020),
    ("Bojhena Shey Bojhena", "song", "Bengali", "calm,comforting", "Soundtrack", "Arijit Singh", 2012),
    ("Tumpa", "song", "Bengali", "happy,upbeat,comedy", "Pop", "Arob Dey Chowdhuri", 2020),
    ("Amake Amar Moto Thakte Dao", "song", "Bengali", "calm,comforting", "Soundtrack", "Anupam Roy", 2010),
    ("Haami", "movie", "Bengali", "comforting,comedy,feel-good", "Drama", "Nandita Roy", 2018),
    ("Open Tee Bioscope", "movie", "Bengali", "friendship,feel-good", "Drama", "Anindya Chatterjee", 2015),
    ("Praktan", "movie", "Bengali", "comforting,hopeful,feel-good", "Drama", "Nandita Roy", 2016),
    ("Zingaat", "song", "Marathi", "excited,upbeat", "Soundtrack", "Ajay-Atul", 2016),
    ("Mala Ved Lagale", "song", "Marathi", "happy,feel-good", "Soundtrack", "Swapnil Bandodkar", 2013),
    ("Man Udhan Varyache", "song", "Marathi", "calm,comforting", "Soundtrack", "Shankar Mahadevan", 2004),
    ("Ventilator", "movie", "Marathi", "comforting,comedy,hopeful", "Drama", "Rajesh Mapuskar", 2016),
    ("Mumbai Pune Mumbai", "movie", "Marathi", "feel-good,comedy", "Romcom", "Satish Rajwade", 2010),
    ("Elizabeth Ekadashi", "movie", "Marathi", "uplifting,feel-good,hopeful", "Drama", "Paresh Mokashi", 2014),
    ("Gallan Goodiyaan", "song", "Punjabi", "happy,upbeat", "Pop", "Various Artists", 2015),
    ("Lover", "song", "Punjabi", "calm,comforting", "Pop", "Diljit Dosanjh", 2021),
    ("Born to Shine", "song", "Punjabi", "excited,upbeat,happy", "Pop", "Diljit Dosanjh", 2020),
    ("Carry On Jatta", "movie", "Punjabi", "comedy,feel-good", "Comedy", "Smeep Kang", 2012),
    ("Chal Mera Putt", "movie", "Punjabi", "comforting,comedy,friendship", "Comedy", "Janjot Singh", 2019),
    ("Shadaa", "movie", "Punjabi", "comedy,feel-good", "Comedy", "Jagdeep Sidhu", 2019),
    ("Moti Veraana", "song", "Gujarati", "calm,comforting", "Folk", "Aishwarya Majmudar", 2018),
    ("Dholida", "song", "Gujarati", "excited,upbeat,happy", "Folk", "Jahnvi Shrimankar", 2022),
    ("Tari Aankh No Afini", "song", "Gujarati", "calm,comforting", "Folk", "Aishwarya Majmudar", 2014),
    ("Chhello Divas", "movie", "Gujarati", "friendship,comedy,feel-good", "Comedy", "Krishnadev Yagnik", 2015),
    ("Hellaro", "movie", "Gujarati", "hopeful,uplifting", "Drama", "Abhishek Shah", 2019),
    ("Bey Yaar", "movie", "Gujarati", "friendship,feel-good,comedy", "Drama", "Abhishek Jain", 2014),
]
