LANGUAGES = ["English", "Hindi", "Tamil", "Telugu", "Malayalam", "Kannada", "Bengali", "Marathi", "Punjabi", "Gujarati"]

SEED_ITEMS = [
    ("Happy", "song", "English", "happy,upbeat,feel-good", "Pop", "Pharrell Williams", 2013),
    ("Good Life", "song", "English", "happy,upbeat,hopeful", "Pop", "OneRepublic", 2010),
    ("Paddington 2", "movie", "English", "comforting,comedy,feel-good", "Comedy", "Paul King", 2017),
    ("The Secret Life of Walter Mitty", "movie", "English", "hopeful,adventure,feel-good", "Adventure", "Ben Stiller", 2013),
    ("Ilahi", "song", "Hindi", "excited,upbeat,hopeful", "Bollywood", "Arijit Singh", 2013),
    ("Kar Har Maidaan Fateh", "song", "Hindi", "uplifting,hopeful", "Bollywood", "Sukhwinder Singh", 2018),
    ("Zindagi Na Milegi Dobara", "movie", "Hindi", "feel-good,friendship,comedy", "Drama", "Zoya Akhtar", 2011),
    ("Queen", "movie", "Hindi", "uplifting,hopeful,comedy", "Drama", "Vikas Bahl", 2013),
    ("Aalaporan Thamizhan", "song", "Tamil", "excited,upbeat,hopeful", "Soundtrack", "A. R. Rahman", 2017),
    ("Mental Manadhil", "song", "Tamil", "happy,upbeat", "Soundtrack", "A. R. Rahman", 2015),
    ("Oh My Kadavule", "movie", "Tamil", "feel-good,comedy,hopeful", "Romcom", "Ashwath Marimuthu", 2020),
    ("Nanban", "movie", "Tamil", "friendship,comedy,uplifting", "Comedy", "Shankar", 2012),
    ("Butta Bomma", "song", "Telugu", "happy,upbeat", "Soundtrack", "Armaan Malik", 2020),
    ("Naatu Naatu", "song", "Telugu", "excited,upbeat", "Soundtrack", "M. M. Keeravani", 2022),
    ("Jathi Ratnalu", "movie", "Telugu", "comedy,feel-good", "Comedy", "Anudeep KV", 2021),
    ("Bommarillu", "movie", "Telugu", "comforting,feel-good,hopeful", "Drama", "Bhaskar", 2006),
    ("Malare", "song", "Malayalam", "calm,comforting", "Soundtrack", "Vijay Yesudas", 2015),
    ("Jimikki Kammal", "song", "Malayalam", "happy,upbeat", "Soundtrack", "Vineeth Sreenivasan", 2017),
    ("Bangalore Days", "movie", "Malayalam", "friendship,feel-good,comforting", "Drama", "Anjali Menon", 2014),
    ("Ustad Hotel", "movie", "Malayalam", "comforting,hopeful,feel-good", "Drama", "Anwar Rasheed", 2012),
    ("Belageddu", "song", "Kannada", "happy,upbeat", "Soundtrack", "Vijay Prakash", 2016),
    ("Karabuu", "song", "Kannada", "excited,upbeat", "Soundtrack", "Chandan Shetty", 2017),
    ("Kirik Party", "movie", "Kannada", "friendship,comedy,feel-good", "Comedy", "Rishab Shetty", 2016),
    ("Sarkari Hi. Pra. Shaale", "movie", "Kannada", "comforting,comedy,hopeful", "Drama", "Rishab Shetty", 2018),
    ("Bojhena Shey Bojhena", "song", "Bengali", "calm,comforting", "Soundtrack", "Arijit Singh", 2012),
    ("Tumpa", "song", "Bengali", "happy,upbeat,comedy", "Pop", "Arob Dey Chowdhuri", 2020),
    ("Haami", "movie", "Bengali", "comforting,comedy,feel-good", "Drama", "Nandita Roy", 2018),
    ("Open Tee Bioscope", "movie", "Bengali", "friendship,feel-good", "Drama", "Anindya Chatterjee", 2015),
    ("Zingaat", "song", "Marathi", "excited,upbeat", "Soundtrack", "Ajay-Atul", 2016),
    ("Mala Ved Lagale", "song", "Marathi", "happy,feel-good", "Soundtrack", "Swapnil Bandodkar", 2013),
    ("Ventilator", "movie", "Marathi", "comforting,comedy,hopeful", "Drama", "Rajesh Mapuskar", 2016),
    ("Mumbai Pune Mumbai", "movie", "Marathi", "feel-good,comedy", "Romcom", "Satish Rajwade", 2010),
    ("Gallan Goodiyaan", "song", "Punjabi", "happy,upbeat", "Pop", "Various Artists", 2015),
    ("Lover", "song", "Punjabi", "calm,comforting", "Pop", "Diljit Dosanjh", 2021),
    ("Carry On Jatta", "movie", "Punjabi", "comedy,feel-good", "Comedy", "Smeep Kang", 2012),
    ("Chal Mera Putt", "movie", "Punjabi", "comforting,comedy,friendship", "Comedy", "Janjot Singh", 2019),
    ("Moti Veraana", "song", "Gujarati", "calm,comforting", "Folk", "Aishwarya Majmudar", 2018),
    ("Dholida", "song", "Gujarati", "excited,upbeat,happy", "Folk", "Jahnvi Shrimankar", 2022),
    ("Chhello Divas", "movie", "Gujarati", "friendship,comedy,feel-good", "Comedy", "Krishnadev Yagnik", 2015),
    ("Hellaro", "movie", "Gujarati", "hopeful,uplifting", "Drama", "Abhishek Shah", 2019),
]
